# Generated by Django 4.2.5 on 2023-09-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
